version: "3"
services:
  app:
    environment:
      - DISPLAY=${DISPLAY}
    build: .
    ipc: host
    network_mode: host
    ports:
      - 8000:8000
    command: python /opt/app/main.py
    devices:
        - /dev/video0:/dev/video0
        - /dev/video1:/dev/video1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
